### ISSUE TITLE
Books I want to read

### ISSUE THREAD

**Issue by CurtisMCook** [SanzaBlancoAkA2C/Treehouse#2]
## TODO

*Books I want to read*

* [ ] Learning Java by Building Android Games
* [ ] Android Programming The Big Nerd Ranch Guide
* [ ] Effective Java
* [ ] Java Puzzlers
* [ ] The Busy Coder's Guide to Android Development

💯 🤓 💻 

cc @SanzaBlanco
